// Mocks generated by Mockito 5.4.6 from annotations
// in allybike/test/offline_data_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:allybike/class/result.class.dart' as _i2;
import 'package:allybike/offline-data/data/offline_data.repository.dart' as _i8;
import 'package:allybike/offline-data/models/image.model.dart' as _i7;
import 'package:allybike/offline-data/models/points.model.dart' as _i6;
import 'package:allybike/offline-data/models/site.model.dart' as _i5;
import 'package:allybike/routes/data/route.repository.dart' as _i3;
import 'package:connectivity_plus/connectivity_plus.dart' as _i9;
import 'package:connectivity_plus_platform_interface/connectivity_plus_platform_interface.dart'
    as _i10;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResult_0<T> extends _i1.SmartFake implements _i2.Result<T> {
  _FakeResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IRouteRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIRouteRepository extends _i1.Mock implements _i3.IRouteRepository {
  MockIRouteRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Result<List<dynamic>>> getRouteByPage(int? page) =>
      (super.noSuchMethod(
            Invocation.method(#getRouteByPage, [page]),
            returnValue: _i4.Future<_i2.Result<List<dynamic>>>.value(
              _FakeResult_0<List<dynamic>>(
                this,
                Invocation.method(#getRouteByPage, [page]),
              ),
            ),
          )
          as _i4.Future<_i2.Result<List<dynamic>>>);

  @override
  _i4.Future<_i2.Result<List<dynamic>>> getRouteOfUserByPage(
    int? page,
    int? idUser,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getRouteOfUserByPage, [page, idUser]),
            returnValue: _i4.Future<_i2.Result<List<dynamic>>>.value(
              _FakeResult_0<List<dynamic>>(
                this,
                Invocation.method(#getRouteOfUserByPage, [page, idUser]),
              ),
            ),
          )
          as _i4.Future<_i2.Result<List<dynamic>>>);

  @override
  _i4.Future<_i2.Result<List<dynamic>>> getRoutesByText(String? text) =>
      (super.noSuchMethod(
            Invocation.method(#getRoutesByText, [text]),
            returnValue: _i4.Future<_i2.Result<List<dynamic>>>.value(
              _FakeResult_0<List<dynamic>>(
                this,
                Invocation.method(#getRoutesByText, [text]),
              ),
            ),
          )
          as _i4.Future<_i2.Result<List<dynamic>>>);

  @override
  _i4.Future<_i2.Result<List<dynamic>>> getRoutesOfUserByText(
    String? text,
    int? idUser,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getRoutesOfUserByText, [text, idUser]),
            returnValue: _i4.Future<_i2.Result<List<dynamic>>>.value(
              _FakeResult_0<List<dynamic>>(
                this,
                Invocation.method(#getRoutesOfUserByText, [text, idUser]),
              ),
            ),
          )
          as _i4.Future<_i2.Result<List<dynamic>>>);

  @override
  _i4.Future<_i2.Result<List<dynamic>>> getRouteByFilter({
    int? idTypeRoute,
    int? idTypeDifficulty,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRouteByFilter, [], {
              #idTypeRoute: idTypeRoute,
              #idTypeDifficulty: idTypeDifficulty,
            }),
            returnValue: _i4.Future<_i2.Result<List<dynamic>>>.value(
              _FakeResult_0<List<dynamic>>(
                this,
                Invocation.method(#getRouteByFilter, [], {
                  #idTypeRoute: idTypeRoute,
                  #idTypeDifficulty: idTypeDifficulty,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Result<List<dynamic>>>);

  @override
  _i4.Future<_i2.Result<List<dynamic>>> getRoutesOfUserByFilter({
    int? idTypeRoute,
    int? idTypeDifficulty,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRoutesOfUserByFilter, [], {
              #idTypeRoute: idTypeRoute,
              #idTypeDifficulty: idTypeDifficulty,
            }),
            returnValue: _i4.Future<_i2.Result<List<dynamic>>>.value(
              _FakeResult_0<List<dynamic>>(
                this,
                Invocation.method(#getRoutesOfUserByFilter, [], {
                  #idTypeRoute: idTypeRoute,
                  #idTypeDifficulty: idTypeDifficulty,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Result<List<dynamic>>>);

  @override
  _i4.Future<_i2.Result<Map<String, dynamic>>> createInitialRoute({
    required String? name,
    required String? descriptions,
    required int? idType,
    required int? idLocation,
    required int? idUser,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createInitialRoute, [], {
              #name: name,
              #descriptions: descriptions,
              #idType: idType,
              #idLocation: idLocation,
              #idUser: idUser,
            }),
            returnValue: _i4.Future<_i2.Result<Map<String, dynamic>>>.value(
              _FakeResult_0<Map<String, dynamic>>(
                this,
                Invocation.method(#createInitialRoute, [], {
                  #name: name,
                  #descriptions: descriptions,
                  #idType: idType,
                  #idLocation: idLocation,
                  #idUser: idUser,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Result<Map<String, dynamic>>>);

  @override
  _i4.Future<_i2.Result<List<dynamic>>> saveSite(_i5.SiteOffline? site) =>
      (super.noSuchMethod(
            Invocation.method(#saveSite, [site]),
            returnValue: _i4.Future<_i2.Result<List<dynamic>>>.value(
              _FakeResult_0<List<dynamic>>(
                this,
                Invocation.method(#saveSite, [site]),
              ),
            ),
          )
          as _i4.Future<_i2.Result<List<dynamic>>>);

  @override
  _i4.Future<_i2.Result<List<dynamic>>> savePoints(
    _i6.PointRouteOffline? points,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#savePoints, [points]),
            returnValue: _i4.Future<_i2.Result<List<dynamic>>>.value(
              _FakeResult_0<List<dynamic>>(
                this,
                Invocation.method(#savePoints, [points]),
              ),
            ),
          )
          as _i4.Future<_i2.Result<List<dynamic>>>);

  @override
  _i4.Future<_i2.Result<List<dynamic>>> saveImageRoute(
    _i7.ImageRouteOffline? image,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveImageRoute, [image]),
            returnValue: _i4.Future<_i2.Result<List<dynamic>>>.value(
              _FakeResult_0<List<dynamic>>(
                this,
                Invocation.method(#saveImageRoute, [image]),
              ),
            ),
          )
          as _i4.Future<_i2.Result<List<dynamic>>>);
}

/// A class which mocks [IOfflineDataRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIOfflineDataRepository extends _i1.Mock
    implements _i8.IOfflineDataRepository {
  MockIOfflineDataRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Result<Map<String, dynamic>>> verifyConnectivityApi() =>
      (super.noSuchMethod(
            Invocation.method(#verifyConnectivityApi, []),
            returnValue: _i4.Future<_i2.Result<Map<String, dynamic>>>.value(
              _FakeResult_0<Map<String, dynamic>>(
                this,
                Invocation.method(#verifyConnectivityApi, []),
              ),
            ),
          )
          as _i4.Future<_i2.Result<Map<String, dynamic>>>);
}

/// A class which mocks [Connectivity].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivity extends _i1.Mock implements _i9.Connectivity {
  MockConnectivity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<List<_i10.ConnectivityResult>> get onConnectivityChanged =>
      (super.noSuchMethod(
            Invocation.getter(#onConnectivityChanged),
            returnValue: _i4.Stream<List<_i10.ConnectivityResult>>.empty(),
          )
          as _i4.Stream<List<_i10.ConnectivityResult>>);

  @override
  _i4.Future<List<_i10.ConnectivityResult>> checkConnectivity() =>
      (super.noSuchMethod(
            Invocation.method(#checkConnectivity, []),
            returnValue: _i4.Future<List<_i10.ConnectivityResult>>.value(
              <_i10.ConnectivityResult>[],
            ),
          )
          as _i4.Future<List<_i10.ConnectivityResult>>);
}
